# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions
# More info on Python, GitHub Actions, and Azure App Service: https://aka.ms/python-webapps-actions

name: Build and deploy Python app to Azure Web App - FlaskyApp

on:
  push:
    branches:
      - main
  workflow_dispatch:
  
permissions:
  security-events: write
  actions: read
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read #This is required for actions/checkout

    steps:
      - uses: actions/checkout@v4

      - name: Set up Python version
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Create and start virtual environment
        run: |
          python -m venv venv
          source venv/bin/activate
      
      - name: Install dependencies
        run: pip install -r requirements.txt
        
      # Optional: Add step to run tests here (PyTest, Django test suites, etc.)

      - name: Zip artifact for deployment
        run: zip release.zip ./* -r

      - name: Upload artifact for deployment jobs
        uses: actions/upload-artifact@v4
        with:
          name: python-app
          path: |
            release.zip
            !venv/
            
             

      - name: OWASP Dependency-Check
        uses: dependency-check/Dependency-Check_Action@main
        with:
            project: 'flasky'
            scan_dir: '.'  # Directory to scan
            format: 'HTML' # Report format (JSON, HTML, SARIF)

      - name: Secrets Scanning
        uses: gitleaks/gitleaks-action@v2

      - name: Checkov IaC Scan
        uses: bridgecrewio/checkov-action@v12

     # - name: Scan Container Image
     #   uses: anchore/scan-action@v3
       # if: startsWith(runs-on, 'ubuntu')

     # - name: OWASP ZAP Scan
    #    uses: zaproxy/action-full-scan@v0.6.0
   #     if: success()
    #    with:
    #      target: ${{ steps.deploy-to-webapp.outputs.webapp-url }}

    #  - name: Check Licenses
    #    uses: fossas/fossa-action@v1

     # - name: Upgrade pip-audit
      #  run: pip install --upgrade pip-audit

     # - name: Run pip-audit (JSON format)
     #   run: pip-audit -f json
        
  analyze:
    name: Analyze
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3
      with:
        fetch-depth: 2

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'

    # Install Python dependencies if needed
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi

    - name: Initialize CodeQL
      uses: github/codeql-action/init@v2
      with:
        languages: 'python'
        # If you have custom queries, add them here
        # queries: +security-and-quality

    - name: Autobuild
      uses: github/codeql-action/autobuild@v2

    - name: Perform CodeQL Analysis
      uses: github/codeql-action/analyze@v2

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'Production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}
    permissions:
      id-token: write #This is required for requesting the JWT
      contents: read #This is required for actions/checkout

    steps:
      - name: Download artifact from build job
        uses: actions/download-artifact@v4
        with:
          name: python-app

      - name: Unzip artifact for deployment
        run: unzip release.zip

      
      - name: Login to Azure
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZUREAPPSERVICE_CLIENTID_98F68F6FA1C34AF8ADC70A3A3EC2073F }}
          tenant-id: ${{ secrets.AZUREAPPSERVICE_TENANTID_5F3498E85B7947B8A296DCAF79973CC1 }}
          subscription-id: ${{ secrets.AZUREAPPSERVICE_SUBSCRIPTIONID_683EF6305A2E4E47A1B5E03F864250F6 }}

      - name: 'Deploy to Azure Web App'
        uses: azure/webapps-deploy@v3
        id: deploy-to-webapp
        with:
          app-name: 'FlaskyApp'
          slot-name: 'Production'
          
